### PR TITLE
fixes to upstream

### PR DESCRIPTION
**Pull request by ulda**
I cherry picked some fixes that  are independent from my gpib-bridge work for upstreaming.

b72aea0 will correct the API, so be aware that outside code has to be fixed with regarding to use of encoding/decoding opaque_data, see example code.

feel free to apply.

### CODE REVIEW

**Comment by ulda** [comment]
I added real SRQ support.

**Comment by coburnw** [comment]
This is going to take me a bit to work thru.  Please know i appreciate the work.

**Comment by ulda** [comment]
By the way, 
Maybe you can check https://github.com/ulda/python-vxi11-server/commit/ac86c2d0523c887a9f491dd35d92c7f641915522 
This is invasive.
But I think you puzzled on this fir long , too?

**Comment by coburnw** [comment]
Ah-ha. So THATS how thats supposed to work.  One for the fix pile.  Thanks!

**Pull request merged**
